version: '3'
services:
  app1:
    build: .
    environment:
      - APP_NAME=App1
    ports:
      - "3002:3001"

  app2:
    build: .
    environment:
      - APP_NAME=App2
    ports:
      - "3003:3001"

  app3:
    build: .
    environment:
      - APP_NAME=App3
    ports:
      - "3004:3001"

